(() => {
  let page=(document.body.dataset.page||location.pathname.split('/').pop().replace('.html','')||'enterprise'); if(page==='vision-hub')page='pauls-vision';
  const hero=document.querySelector('.hero,.vision-hero,.stage');
  if(!hero) return;
  const defs={
    enterprise:{title:'Enterprise Digital Twin',chips:['Projects synchronized','Evidence attached','Governance active'],corner:'REALITY → INTELLIGENCE → ACTION'},
    executive:{title:'Decision Constellation',chips:['14 projects observed','2 decision signals','Thresholds applied'],corner:'SIGNAL COMPRESSION • LEADERSHIP VIEW'},
    project:{title:'Living Jobsite Scan',chips:['Look-ahead loaded','Drawing layer aligned','RFI hotspot tracked'],corner:'FIELD → PLAN → CONSTRAINT → ACTION'},
    preconstruction:{title:'Scope Layer Engine',chips:['Drawing layer','Specification layer','Bid coverage layer'],corner:'COMPARE • ALIGN • EXPOSE GAPS'},
    finance:{title:'Forecast Geometry',chips:['Cost signal live','Schedule effect linked','Scenario plane ready'],corner:'CAUSE → FINANCIAL EFFECT → CHOICE'},
    people:{title:'Workforce Constellation',chips:['Demand mapped','Experience indexed','Availability watched'],corner:'CAPABILITY → NEED → MATCH'},
    it:{title:'Governed Data Fabric',chips:['Identity verified','Policy gate online','Audit stream active'],corner:'SOURCE → POLICY → EVIDENCE → ROLE'},
    studio:{title:'Idea Forge',chips:['Idea captured','Risk tier assigned','Pilot path ready'],corner:'IDEA → PROTOTYPE → PILOT → SCALE'},
    journey:{title:'Transformation Corridor',chips:['Discover','Prove','Scale'],corner:'LEARN → PILOT → MEASURE → EXPAND'},
    'business-case':{title:'Value Field',chips:['Pilot evidence','Measured outcomes','Investment signal'],corner:'PROOF → VALUE → DECISION'},
    'pauls-vision':{title:'Columbia Intelligence Fabric',chips:['One foundation','Role-aware experiences','Human authority'],corner:'PAUL’S AI VISION • LIVING SYSTEM'},
    demo:{title:'Cinematic Signal Route',chips:['One event','Every role','Evidence follows'],corner:'LIVE DEMO • COLUMBIA NERVOUS SYSTEM'},
    index:{title:'Columbia AI Concept',chips:['People','Data','Construction'],corner:'SAME INDUSTRY • BIGGER POSSIBILITIES'}
  };
  const key=page==='pauls-vision'||page==='demo'||page==='index'?page:page; const d=defs[key]||defs.enterprise;
  const layer=document.createElement('div');layer.className='future-fabric';
  layer.innerHTML = page==='demo' ? `<canvas aria-hidden="true"></canvas><div class="future-corner">${d.corner}</div>` : `<canvas aria-hidden="true"></canvas><div class="future-hud"><div class="ff-title">${d.title}</div>${d.chips.map(x=>`<div class="ff-chip">${x}</div>`).join('')}</div><div class="future-corner">${d.corner}</div>`;
  hero.appendChild(layer);
  const c=layer.querySelector('canvas'),ctx=c.getContext('2d');
  const reduce=matchMedia('(prefers-reduced-motion:reduce)').matches;
  let W=0,H=0,DPR=Math.min(devicePixelRatio||1,2),t=0,raf;
  const resize=()=>{const r=hero.getBoundingClientRect();W=Math.max(1,r.width);H=Math.max(1,r.height);c.width=W*DPR;c.height=H*DPR;c.style.width=W+'px';c.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)};resize();addEventListener('resize',resize,{passive:true});
  const line=(a,b,alpha=.35,width=1)=>{ctx.strokeStyle=`rgba(58,214,255,${alpha})`;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke()};
  const dot=(x,y,r=3,col='72,225,255',a=.8)=>{ctx.fillStyle=`rgba(${col},${a})`;ctx.shadowColor=`rgba(${col},.7)`;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0};
  const grid=(persp=false)=>{ctx.strokeStyle='rgba(56,173,213,.08)';ctx.lineWidth=1;if(persp){const vy=H*.34;for(let i=0;i<13;i++){const x=W*.48+i*W*.045;line([x,vy],[W*.52+(x-W*.52)*2.1,H],.07)}for(let y=0;y<8;y++){const yy=vy+(H-vy)*(y/8)**1.65;line([W*.42,yy],[W,yy],.07)}}else{for(let x=0;x<W;x+=38)line([x,0],[x,H],.045);for(let y=0;y<H;y+=38)line([0,y],[W,y],.045)}};
  const building=()=>{const cx=W*.76,cy=H*.62,s=Math.min(W,H)*.22,ang=t*.00018;grid(true);let pts=[];for(let z=0;z<5;z++){const yy=cy-z*s*.24;const ww=s*(1-z*.035);const off=Math.sin(ang+z*.3)*7;const q=[[cx-ww*.55+off,yy],[cx+ww*.52+off,yy-ww*.16],[cx+ww*.52+off,yy-ww*.88],[cx-ww*.55+off,yy-ww*.72]];pts.push(q);q.forEach((p,i)=>line(p,q[(i+1)%4],.42,1.1));if(z>0)q.forEach((p,i)=>line(p,pts[z-1][i],.22))}for(let f=0;f<7;f++){const yy=cy-s*.18-f*s*.12;line([cx-s*.52,yy],[cx+s*.5,yy-s*.12],.13)}const sy=(t/22)%Math.max(H,1);ctx.fillStyle='rgba(63,220,255,.06)';ctx.fillRect(W*.52,sy-3,W*.46,6);dot(cx,cy-s*1.05,4,'66,240,190',.9)};
  const constellation=(people=false)=>{grid(false);const cx=W*.77,cy=H*.52;const N=people?14:9;let p=[];for(let i=0;i<N;i++){const a=i/N*Math.PI*2+t*.00009*(i%2?1:-1);const rad=(people?75:62)+(i%3)*22;p.push([cx+Math.cos(a)*rad,cy+Math.sin(a)*rad*.55])}p.forEach((q,i)=>{for(let j=i+1;j<p.length;j++)if(Math.hypot(q[0]-p[j][0],q[1]-p[j][1])<95)line(q,p[j],.12);dot(q[0],q[1],i%4===0?4:2.5,i%5===0?'255,205,90':'68,221,255',.8)});ctx.strokeStyle='rgba(65,220,255,.22)';ctx.beginPath();ctx.arc(cx,cy,38+Math.sin(t*.002)*4,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(cx,cy,70,0,Math.PI*2);ctx.stroke();dot(cx,cy,5,'68,240,188',1)};
  const blueprint=()=>{grid(false);ctx.save();ctx.translate(W*.58,H*.22);ctx.rotate(-.04);for(let i=0;i<6;i++){ctx.strokeStyle=`rgba(65,220,255,${.15+i*.025})`;ctx.strokeRect(i*24,i*13,W*.34-i*38,H*.5-i*24)}for(let i=0;i<10;i++)line([W*.58+i*32,H*.27],[W*.52+i*25,H*.67],.12);ctx.restore();const scan=(t/14)%(H*.55);ctx.fillStyle='rgba(71,221,255,.07)';ctx.fillRect(W*.52,H*.18+scan,W*.42,4);dot(W*.78,H*.48,6,'255,91,114',.95);ctx.fillStyle='rgba(255,92,115,.85)';ctx.font='700 8px Inter,Arial';ctx.fillText('RFI / CONSTRAINT',W*.79,H*.47)};
  const layers=()=>{grid(false);const baseX=W*.6,baseY=H*.3;for(let k=0;k<3;k++){ctx.save();ctx.translate(k*32,-k*24);ctx.strokeStyle=`rgba(${k===2?'255,205,94':'62,214,255'},${.25+k*.12})`;ctx.strokeRect(baseX,baseY,W*.28,H*.34);for(let i=1;i<5;i++)line([baseX+i*W*.055,baseY],[baseX+i*W*.055,baseY+H*.34],.10);for(let j=1;j<4;j++)line([baseX,baseY+j*H*.07],[baseX+W*.28,baseY+j*H*.07],.10);ctx.restore()}const x=baseX+W*.18+Math.sin(t*.001)*8,y=baseY+H*.16;dot(x,y,6,'255,96,116',.95);ctx.fillStyle='rgba(255,95,116,.75)';ctx.font='700 8px Inter,Arial';ctx.fillText('SCOPE GAP',x+10,y+3)};
  const finance=()=>{grid(true);const x0=W*.5,y0=H*.64;ctx.strokeStyle='rgba(54,214,255,.5)';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<9;i++){const x=x0+i*W*.055,y=y0-Math.sin(i*.9+t*.0013)*22-i*4;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();ctx.strokeStyle='rgba(255,91,116,.8)';ctx.beginPath();for(let i=7;i<12;i++){const x=x0+i*W*.055,y=y0+16+(i-7)*13+Math.sin(i+t*.001)*4;if(i===7)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();for(let i=0;i<6;i++){const h=24+i*8+Math.sin(t*.001+i)*6;ctx.fillStyle='rgba(60,213,255,.16)';ctx.fillRect(W*.58+i*31,H*.75-h,18,h)}};
  const dataFabric=()=>{grid(false);const xs=[W*.55,W*.62,W*.69],ys=[H*.28,H*.51,H*.73];xs.forEach((x,i)=>{ys.forEach((y,j)=>{dot(x,y,4,j===1?'68,239,188':'66,220,255',.9);line([x,y],[W*.79,H*.5],.18)})});ctx.strokeStyle='rgba(68,239,188,.48)';ctx.strokeRect(W*.75,H*.38,W*.08,H*.24);ctx.fillStyle='rgba(67,238,188,.9)';ctx.font='700 8px Inter,Arial';ctx.fillText('POLICY',W*.765,H*.505);dot(W*.89,H*.5,6,'66,220,255',1);line([W*.83,H*.5],[W*.89,H*.5],.5,2);const p=(t*.00032)%1;dot(W*.55+(W*.34)*p,H*.28+(H*.22)*Math.sin(p*Math.PI),3,'255,210,95',1)};
  const forge=()=>{grid(false);const cx=W*.77,cy=H*.52;for(let r=28;r<100;r+=22){ctx.strokeStyle=`rgba(64,220,255,${.13+r/700})`;ctx.beginPath();ctx.arc(cx,cy,r+Math.sin(t*.001+r)*3,0,Math.PI*2);ctx.stroke()}for(let i=0;i<14;i++){const a=i*.7+t*.0004;dot(cx+Math.cos(a)*(110+(i%3)*15),cy+Math.sin(a)*(55+(i%3)*8),2.5,i%4===0?'255,205,92':'66,220,255',.75);line([cx,cy],[cx+Math.cos(a)*65,cy+Math.sin(a)*32],.08)}dot(cx,cy,7,'67,240,188',1)};
  const journey=()=>{grid(true);const y=H*.65;const stages=['DISCOVER','PILOT','PROVE','SCALE','TRANSFORM'];stages.forEach((s,i)=>{const x=W*.49+i*W*.105;dot(x,y-i*10,4,i<3?'68,239,188':'66,220,255',.9);if(i<4)line([x,y-i*10],[x+W*.105,y-(i+1)*10],.35,2);ctx.fillStyle='rgba(147,211,232,.7)';ctx.font='700 7px Inter,Arial';ctx.fillText(s,x-18,y-i*10+20)});const p=(t*.00023)%1;const seg=p*4,idx=Math.floor(seg),q=seg-idx;const x=W*.49+(idx+q)*W*.105,yy=y-(idx+q)*10;dot(x,yy,5,'255,211,91',1)};
  const value=()=>{grid(true);for(let i=0;i<7;i++){const h=28+i*13+Math.sin(t*.001+i)*4;const x=W*.57+i*W*.052;ctx.fillStyle=`rgba(64,218,255,${.12+i*.035})`;ctx.fillRect(x,H*.72-h,18,h);ctx.strokeStyle='rgba(77,225,255,.25)';ctx.strokeRect(x,H*.72-h,18,h)}ctx.strokeStyle='rgba(68,240,188,.7)';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<7;i++){const x=W*.57+i*W*.052,y=H*.62-i*13+Math.sin(t*.001+i)*3;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()};
  const draw=()=>{t=performance.now();ctx.clearRect(0,0,W,H);ctx.globalCompositeOperation='source-over';if(page==='enterprise'||page==='index'||page==='pauls-vision')building();else if(page==='demo')dataFabric();else if(page==='executive')constellation(false);else if(page==='project')blueprint();else if(page==='preconstruction')layers();else if(page==='finance')finance();else if(page==='people')constellation(true);else if(page==='it')dataFabric();else if(page==='studio')forge();else if(page==='journey')journey();else if(page==='business-case')value();if(!reduce)raf=requestAnimationFrame(draw)};draw();
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&raf)cancelAnimationFrame(raf);else if(!document.hidden&&!reduce)draw()});
})();
