(() => {
  const page=document.body.dataset.page||'enterprise';
  const roleName={enterprise:'Enterprise',executive:'Executive',project:'Project',preconstruction:'Preconstruction',finance:'Finance',people:'People',it:'IT & Knowledge',studio:'Studio',journey:'Journey','business-case':'Business Case'}[page]||'Enterprise';
  const xray=document.querySelector('.xray-workspace'); if(!xray) return;
  const shell=xray.querySelector('.xray-shell'); if(!shell) return;
  const sources=[...xray.querySelectorAll('.xray-source b')].map(n=>n.textContent.trim());
  const currentRole=(xray.querySelector('.xray-stat b')?.textContent||roleName).trim();
  const classif=(xray.querySelectorAll('.xray-stat b')[1]?.textContent||'Internal — governed').trim();
  const src=sources.length?sources:['Approved source A','Approved source B','Approved source C','Approved source D'];
  const evidence=src.slice(0,4).map((s,i)=>({name:s,authority:i===0?'Authoritative':'Approved context',fresh:i===0?'Live / current':i===1?'15 min ago':'Today',confidence:[94,88,82,76][i]||74,reason:i===0?'Directly supports the primary signal.':i===1?'Corroborates timing, context or financial impact.':'Adds supporting context only when the request intersects this source.',sample:{record:`${roleName.toUpperCase()}-${214+i*17}`,scope:page,classification:classif,source:s,matched_fields:['project_id','status','owner','updated_at'].slice(0,3+(i%2)),retrieval:'role + entity scoped'}}));
  const lab=document.createElement('section'); lab.className='xr-lab';
  const sourceNodes=src.map((s,i)=>`<g><rect class="node" x="35" y="${55+i*72}" width="170" height="46" rx="9"/><text x="50" y="${74+i*72}">${s.replace(/&/g,'&amp;').slice(0,23)}</text><text class="sub" x="50" y="${90+i*72}">${i===0?'authoritative':'approved role source'}</text><path class="edge ${i===0?'hot':''}" d="M205 ${78+i*72} C275 ${78+i*72}, 285 175, 355 175"/></g>`).join('');
  lab.innerHTML=`
    <div class="xr-lab-top"><strong>X-Ray Lab • ${roleName}</strong><small>Useful transparency, not hidden chain-of-thought</small>
      <button class="xr-lab-tab active" data-xr-tab="map">Access map</button><button class="xr-lab-tab" data-xr-tab="roles">Compare roles</button><button class="xr-lab-tab" data-xr-tab="evidence">Evidence inspector</button><button class="xr-lab-tab" data-xr-tab="audit">Audit + controls</button><button class="xr-lab-tab" data-xr-tab="sim">Test a request</button>
    </div>
    <div class="xr-lab-pane active" data-xr-pane="map"><div class="xr-map-grid">
      <div class="xr-lineage-wrap"><svg class="xr-lineage-svg" viewBox="0 0 800 410" preserveAspectRatio="none">
        ${sourceNodes}
        <rect class="node gate" x="355" y="147" width="150" height="56" rx="11"/><text x="377" y="169">POLICY GATE</text><text class="sub" x="377" y="187">identity • role • classification</text>
        <path class="edge hot" d="M505 175 C555 175,555 110,600 110"/><path class="edge hot" d="M505 175 C555 175,555 250,600 250"/>
        <rect class="node core" x="600" y="78" width="165" height="64" rx="12"/><text x="621" y="102">EVIDENCE INDEX</text><text class="sub" x="621" y="121">ranked + attributable records</text>
        <rect class="node core" x="600" y="218" width="165" height="64" rx="12"/><text x="621" y="242">CHIEF / ROLE AI</text><text class="sub" x="621" y="261">compose + cite + recommend</text>
        <path class="edge hot" d="M682 142 L682 218"/><path class="edge hot" d="M682 282 C682 330,525 330,525 374"/>
        <rect class="node gate" x="435" y="350" width="180" height="42" rx="10"/><text x="458" y="373">HUMAN ACTION BOUNDARY</text>
        <path class="edge blocked" d="M205 365 C290 365,305 315,355 315"/><text class="sub" x="220" y="355">blocked cross-role path</text>
        <circle class="xr-packet" r="5"><animateMotion dur="2.6s" repeatCount="indefinite" path="M205 78 C275 78,285 175,355 175 C555 175,555 110,600 110 L682 142 L682 218 C682 330,525 330,525 374"/></circle>
      </svg></div>
      <div class="xr-side-stack"><div class="xr-mini"><h4>Source health</h4><div class="xr-health">${src.slice(0,4).map((s,i)=>`<div class="xr-health-row ${i===3?'warn':''}"><span>${s}</span><i></i><small>${i===0?'Authoritative • current':'Approved • '+(i===3?'sync review due':'healthy')}</small></div>`).join('')}</div></div>
      <div class="xr-mini"><h4>Why this request was allowed</h4><div class="xr-rule-list"><div><i></i><span>Identity resolved to <b>${currentRole}</b>.</span></div><div><i></i><span>Requested data intersects the role’s approved scope.</span></div><div><i></i><span>Restricted cross-role data is excluded before retrieval.</span></div><div><i></i><span>Any business commitment remains human-approved.</span></div></div></div>
      <div class="xr-mini"><h4>Live controls</h4><button class="xray-btn primary" data-xr-replay>Replay data route</button> <button class="xray-btn" data-xr-block>Show blocked path</button></div></div>
    </div></div>
    <div class="xr-lab-pane" data-xr-pane="roles"><div class="xr-role-compare">
      ${['Executive','Project','Finance','People','IT / Governance','Preconstruction','Studio','Enterprise'].map(r=>{const cur=currentRole.toLowerCase().includes(r.split(' ')[0].toLowerCase())||roleName.toLowerCase().includes(r.split(' ')[0].toLowerCase());const financial=r==='Finance'||r==='Executive';const people=r==='People';return `<div class="xr-role-card ${cur?'current':''}"><b>${r}${cur?' • current':''}</b><span>Project status <em>Read</em></span><span>Financial detail <em class="${financial?'':'block'}">${financial?'Scoped':'Blocked'}</em></span><span>People detail <em class="${people?'':'block'}">${people?'Scoped':'Blocked'}</em></span><span>Commit action <em class="block">Human</em></span></div>`}).join('')}
    </div><div class="xr-mini" style="margin-top:12px"><h4>Design principle</h4><div class="xr-why">Personal AI by role does not mean copying all company data into every experience. The same governed foundation can return different slices of evidence because the user, job, project, classification and action boundary are different.</div></div></div>
    <div class="xr-lab-pane" data-xr-pane="evidence"><div class="xr-inspector"><div class="xr-evidence-list">${evidence.map((e,i)=>`<button class="xr-evidence-btn ${i===0?'active':''}" data-ev="${i}"><b>${e.name}</b><small>${e.authority} • ${e.fresh} • ${e.confidence}% relevance</small></button>`).join('')}</div><div class="xr-detail" data-ev-detail></div></div></div>
    <div class="xr-lab-pane" data-xr-pane="audit"><div class="xr-audit"><div class="xr-timeline"><h3 style="margin:0 0 8px">Request audit trail</h3>
      <div class="xr-audit-row"><time>10:42:01</time><i></i><div><b>Session identity resolved</b><span>${currentRole} • concept session</span></div><em>PASS</em></div>
      <div class="xr-audit-row"><time>10:42:01</time><i></i><div><b>Policy package evaluated</b><span>Role, project, classification and action type checked</span></div><em>ALLOW</em></div>
      <div class="xr-audit-row"><time>10:42:02</time><i></i><div><b>Scoped retrieval executed</b><span>${src.length} approved source families available; only relevant records returned</span></div><em>TRACE</em></div>
      <div class="xr-audit-row"><time>10:42:03</time><i></i><div><b>Evidence packet assembled</b><span>Record identifiers retained for verification</span></div><em>CITED</em></div>
      <div class="xr-audit-row"><time>10:42:04</time><i></i><div><b>Recommendation drafted</b><span>No external system write executed</span></div><em>DRAFT</em></div>
      <div class="xr-audit-row"><time>10:42:04</time><i></i><div><b>Audit event committed</b><span>Request ID, policy decision and evidence set preserved</span></div><em>LOGGED</em></div>
      </div><div class="xr-policy-card"><h4>Control snapshot</h4><div class="xr-policy-kpis"><div><small>Policy</small><b>v3.4</b></div><div><small>Access result</small><b style="color:#54ebbe">Allowed</b></div><div><small>Write access</small><b>Draft only</b></div><div><small>Human gate</small><b>Required</b></div></div><div class="xr-mini" style="margin-top:10px"><h4>Audit packet includes</h4><div class="xr-rule-list"><div><i></i><span>Request + resolved role</span></div><div><i></i><span>Policy version + access result</span></div><div><i></i><span>Source identifiers + evidence metadata</span></div><div><i></i><span>Prepared recommendation + action boundary</span></div></div></div><button class="xray-btn xr-download" data-xr-export>Export illustrative audit packet</button></div></div></div>
    <div class="xr-lab-pane" data-xr-pane="sim"><div class="xr-sim"><div class="xr-sim-controls"><div class="xr-field"><label>Act as role</label><select data-xr-role><option>${currentRole}</option><option>Executive</option><option>Project / Superintendent</option><option>Finance</option><option>People / HR</option><option>IT / Governance</option></select></div><div class="xr-field"><label>Request</label><textarea data-xr-query>${xray.querySelector('.xray-request .big')?.textContent.replace(/[“”]/g,'')||'Show me the role-relevant signal and supporting evidence.'}</textarea></div><button class="xray-btn primary" data-xr-test>Evaluate request</button></div><div class="xr-sim-result" data-xr-result></div></div></div>`;
  shell.appendChild(lab);
  const tabs=[...lab.querySelectorAll('[data-xr-tab]')],panes=[...lab.querySelectorAll('[data-xr-pane]')];
  tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.toggle('active',x===b));panes.forEach(p=>p.classList.toggle('active',p.dataset.xrPane===b.dataset.xrTab));});
  const map=lab.querySelector('.xr-lineage-wrap');
  lab.querySelector('[data-xr-replay]').onclick=()=>{map.classList.remove('running');void map.offsetWidth;map.classList.add('running');setTimeout(()=>map.classList.remove('running'),5200)};
  lab.querySelector('[data-xr-block]').onclick=()=>{const e=map.querySelector('.edge.blocked');e.style.strokeWidth='4';e.style.filter='drop-shadow(0 0 8px #ff5d73)';setTimeout(()=>{e.style.strokeWidth='';e.style.filter=''},1800)};
  const detail=lab.querySelector('[data-ev-detail]');
  function showEv(i){const e=evidence[i];detail.innerHTML=`<h3>${e.name}</h3><div class="meta"><span>${e.authority}</span><span>${e.fresh}</span><span>${e.confidence}% relevance</span><span>${classif}</span></div><div class="xr-why"><b>Why this evidence is here:</b> ${e.reason}</div><pre>${JSON.stringify(e.sample,null,2)}</pre><div class="xr-rule-list"><div><i></i><span>Source identifier preserved.</span></div><div><i></i><span>Retrieved because it matched the allowed entity scope.</span></div><div><i></i><span>Record can be opened or verified before action.</span></div></div>`}
  showEv(0); lab.querySelectorAll('[data-ev]').forEach(b=>b.onclick=()=>{lab.querySelectorAll('[data-ev]').forEach(x=>x.classList.toggle('active',x===b));showEv(+b.dataset.ev)});
  const result=lab.querySelector('[data-xr-result]');
  const evalReq=()=>{const r=lab.querySelector('[data-xr-role]').value.toLowerCase(),q=lab.querySelector('[data-xr-query]').value.toLowerCase();let blocked=false,reason='The request stays within the selected role’s governed information boundary.';if((q.includes('salary')||q.includes('employee medical')||q.includes('performance review'))&&!r.includes('people')){blocked=true;reason='People-restricted information is outside this role’s approved scope.'}if((q.includes('profit')||q.includes('margin')||q.includes('cash')||q.includes('financial'))&&!(r.includes('finance')||r.includes('executive'))){blocked=true;reason='Detailed financial data is restricted to Finance / authorized executive scope.'}if(q.includes('change permission')||q.includes('disable audit')||q.includes('bypass')){blocked=true;reason='The request attempts to alter or bypass a governance control.'}result.innerHTML=`<span class="xr-result-badge ${blocked?'blocked':''}">${blocked?'BLOCKED':'ALLOWED WITH SCOPE'}</span><h2>${blocked?'Chief should refuse this request.':'Chief may continue to approved retrieval.'}</h2><p>${reason}</p><div class="xr-rule-list"><div><i class="${blocked?'block':''}"></i><span>Identity: ${lab.querySelector('[data-xr-role]').value}</span></div><div><i class="${blocked?'block':''}"></i><span>Classification: ${classif}</span></div><div><i class="${blocked?'block':''}"></i><span>${blocked?'No restricted source retrieval occurs.':'Only role-approved sources are eligible for retrieval.'}</span></div><div><i></i><span>Human approval remains required for any business commitment.</span></div></div>`};
  lab.querySelector('[data-xr-test]').onclick=evalReq;evalReq();
  lab.querySelector('[data-xr-export]').onclick=()=>{const packet={concept:true,request_id:'COL-XR-'+Date.now(),role:currentRole,page,classification:classif,policy_version:'3.4-illustrative',access_result:'allowed',sources:src,evidence:evidence.map(e=>({source:e.name,authority:e.authority,freshness:e.fresh,relevance:e.confidence})),action_boundary:'human approval required'};const blob=new Blob([JSON.stringify(packet,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`columbia-xray-${page}-audit.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
  // Auto-run the visual route whenever X-Ray opens, without changing the original X-Ray behavior.
  document.querySelectorAll('.pv-mini-xray').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{map.classList.add('running');setTimeout(()=>map.classList.remove('running'),5200)},450)));
})();
